apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config # Nombre del ConfigMap
data:
  grafana.ini: |
    [paths]
      provisioning: /etc/grafana/provisioning # Directorio de provisionamiento
    [dashboards]
      enabled: true # Habilita la carga de dashboards desde archivos
      label: grafana_dashboard # Etiqueta para detectar los dashboards
      label_value: '1' # Valor de la etiqueta
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus # Configura un origen de datos Prometheus
      type: prometheus # Tipo de origen de datos
      url: http://prometheus-service:9090 # URL del servicio Prometheus
      access: proxy
      isDefault: true # Establece este origen como el por defecto
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1 # ID de la organización
      folder: '' # Carpeta para los dashboards
      type: file # Tipo de provisionamiento, por archivos
      disableDeletion: false # Permite la eliminación de dashboards
      editable: true # Permite editar los dashboards
      allowUiUpdates: true # Permite la actualización de la UI
      options:
        path: /var/lib/grafana/dashboards # Ruta a los archivos de dashboards
        foldersFromFilesStructure: true # Permite usar carpetas en la estructura de archivos