apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector-config # Nombre del ConfigMap
  labels:
    app: opentelemetry-collector # Etiqueta de la app
data:
  config.yaml: |
    receivers: # Configuración de receptores
      otlp:
        protocols:
          grpc:
          http:
    processors: # Configuración de procesadores
      batch:
        timeout: 10s # Tiempo de espera del batch processor

    exporters: # Configuración de exporters
      prometheus:
        endpoint: "0.0.0.0:8889" # Endpoint para las métricas de Prometheus
        namespace: "images-api" # Namespace para las métricas
        const_labels:
          label1: "this-is-a-constant-label"
      debug: # Configuración del exporter para debug
        verbosity: detailed # Nivel de verbosidad

    service:
      pipelines:
        traces:
          receivers: [otlp] # Recibe traces del protocolo OTLP
          processors: [batch] # Procesa los traces en batches
          exporters: [debug] # Exporta los traces con el exporter de debug
        metrics:
          receivers: [otlp] # Recibe métricas del protocolo OTLP
          processors: [batch] # Procesa las métricas en batches
          exporters: [prometheus, debug] # Exporta las métricas con el exporter de prometheus y debug