apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment # Nombre del deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine # Imagen de redis
        ports:
        - containerPort: 6379 # Puerto del contenedor
        volumeMounts:
        - name: redis-data # Monta el volumen en /data
          mountPath: /data
      volumes:
      - name: redis-data # Volumen para datos de redis
        emptyDir: {} # Usa un directorio vacío (almacenamiento no persistente)