apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv # Nombre del PersistentVolume
spec:
  storageClassName: local-storage # Clase de almacenamiento
  capacity:
    storage: 2Gi # Capacidad del volumen
  accessModes:
    - ReadWriteMany # Modo de acceso
  hostPath:
    path: /data/sqlite # Ruta en el host