apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-api-deployment
  namespace: convertidor-imagenes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images-api
  template:
    metadata:
      labels:
        app: images-api
    spec:
      initContainers:
        - name: clear-stale-sockets
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              rm -vrf /data/uploads/*
              rm -vrf /data/temp-uploads/*
        - name: volume-permissions
          image: busybox:latest
          command: ["/bin/chmod", "-R", "777", "/data"]
          volumeMounts:
            - name: sqlite-volume
              mountPath: /data/sqlite
        
      containers:
        - name: images-api-container
          image: dmolmar/images-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: secret-key
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: DATABASE_URL
              value: "sqlite:////data/sqlite/images.db"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          volumeMounts:
            - name: uploads
              mountPath: /data/uploads
            - name: temp-uploads
              mountPath: /data/temp-uploads
            - name: sqlite-volume
              mountPath: /data/sqlite
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc
        - name: temp-uploads
          persistentVolumeClaim:
            claimName: temp-uploads-pvc
        - name: sqlite-volume
          persistentVolumeClaim:
             claimName: sqlite-pvc