apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-api-deployment
  namespace: convertidor-imagenes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: images-api
  template:
    metadata:
      labels:
        app: images-api
    spec:
      initContainers:
        - name: clear-stale-sockets
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              rm -vrf /app/uploads/*
              rm -vrf /app/temp_uploads/*
      containers:
        - name: images-api-container
          image: dmolmar/images-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: secret-key
            - name: REDIS_URL
              value: "redis://redis-service:6379"
          resources:
            requests:
              cpu: "100m"   # Lowered request to 100m (adjust as needed)
              memory: "256Mi" # Adjust as needed
            limits:
              cpu: "1000m"  # Increased limit to 3000m (3 cores)
              memory: "1Gi" # Adjust as needed
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
            - name: temp-uploads
              mountPath: /app/temp_uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc
        - name: temp-uploads
          persistentVolumeClaim:
            claimName: temp-uploads-pvc