apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-api-deployment
spec:
  replicas: 1  # Adjust as needed for your web server
  selector:
    matchLabels:
      app: images-api
  template:
    metadata:
      labels:
        app: images-api
    spec:
      containers:
      - name: images-api-container
        image: your-docker-registry/images-api:latest  # Replace with your image
        ports:
        - containerPort: 5000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret-key
        # Add REDIS_URL environment variable
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        - name: temp-uploads
          mountPath: /app/temp_uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc
      - name: temp-uploads
        persistentVolumeClaim:
          claimName: temp-uploads-pvc