apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector-config
  labels:
    app: opentelemetry-collector
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
        timeout: 10s

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889" # Expose Prometheus metrics on this port
        namespace: "images-api"
        const_labels:
          label1: "this-is-a-constant-label"
      logging:
        loglevel: info
      jaeger:
        endpoint: jaeger-all-in-one-collector:14250 # Update with your Jaeger endpoint if it's different
        insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger, logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus, logging]