apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector-config
  labels:
    app: opentelemetry-collector
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
        timeout: 10s

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: "images-api"
        const_labels:
          label1: "this-is-a-constant-label"
      debug: # Changed from logging to debug
        verbosity: detailed  # Add verbosity level

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug] # Changed from logging to debug
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus, debug] # Changed from logging to debug