apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage # Add storage class name
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temp-uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage # Add storage class name
  resources:
    requests:
      storage: 1Gi