apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/sqlite