apiVersion: v1
kind: PersistentVolume
metadata:
  name: temp-uploads-pv  # Use temp-uploads (no underscore)
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/temp-uploads  # Use temp-uploads (no underscore)