apiVersion: v1
kind: PersistentVolume
metadata:
  name: temp-uploads-pv  # Nombre del PersistentVolume
spec:
  storageClassName: local-storage # Clase de almacenamiento
  capacity:
    storage: 1Gi # Capacidad del volumen
  accessModes:
    - ReadWriteMany # Modo de acceso
  hostPath:
    path: /data/temp-uploads  # Ruta en el host