apiVersion: v1
kind: PersistentVolume
metadata:
  name: temp-uploads-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi  # Changed to 1Gi to match the temp-uploads-pvc requirement
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/temp-uploads