apiVersion: v1
kind: PersistentVolume
metadata:
  name: temp-uploads-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.1
    path: /home/alexander/proyecto-diciembre/convertidor-imagenes-web/data/nfs/temp-uploads