apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi  # Changed to 5Gi to match the uploads-pvc requirement
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/uploads