apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 3 # Initial number, managed by HPA
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values: [] # Will be dynamically populated by the script or operator
      containers:
      - name: worker-container
        image: your-docker-registry/images-api:latest # Replace with your image
        command: ["python", "-u", "worker.py"]
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret-key
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        resources:
          requests:
            cpu: "800m"
            memory: "512Mi"
          limits:
            cpu: "900m"
            memory: "1Gi"
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        - name: temp-uploads
          mountPath: /app/temp_uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc
      - name: temp-uploads
        persistentVolumeClaim:
          claimName: temp-uploads-pvc