apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: convertidor-imagenes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - worker
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: worker-container
        image: dmolmar/images-api:latest # Use your image here
        imagePullPolicy: Always
        command: ["python", "worker.py"]
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret-key
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        resources:
          requests:
            cpu: "500m"  # Lowered request to 500m
            memory: "512Mi" # Adjust as needed
          limits:
            cpu: "750m"  # Lowered limit to 750m (0.75 cores)
            memory: "1Gi" # Adjust as needed
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        - name: temp-uploads
          mountPath: /app/temp_uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc
      - name: temp-uploads
        persistentVolumeClaim:
          claimName: temp-uploads-pvc