apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: convertidor-imagenes
spec:
  replicas: 9
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - worker
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: worker-container
        image: dmolmar/images-api:latest
        imagePullPolicy: Always
        command: ["python", "worker.py"]
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret-key
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "750m"
            memory: "1Gi"
        volumeMounts:
        - name: uploads
          mountPath: /data/uploads
        - name: temp-uploads
          mountPath: /data/temp-uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc
      - name: temp-uploads
        persistentVolumeClaim:
          claimName: temp-uploads-pvc