apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-hpa # Nombre del HPA
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-deployment # Deployment al que se escalará
  minReplicas: 1 # Número mínimo de réplicas
  maxReplicas: 9 # Número máximo de réplicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Porcentaje de uso de CPU para escalar