apiVersion: v1
kind: Service
metadata:
  name: traefik # Nombre del servicio
  namespace: convertidor-imagenes # Namespace
spec:
  type: NodePort  # Tipo de servicio, NodePort para acceso fuera del cluster
  selector:
    app: traefik # Selector de pods
  ports:
    - protocol: TCP
      port: 80 # Puerto del servicio
      name: web
      targetPort: 80 # Puerto del contenedor
      nodePort: 30080 # Puerto expuesto en el nodo
    - protocol: TCP
      port: 8080 # Puerto del servicio
      name: admin
      targetPort: 8080 # Puerto del contenedor